# Serves the trained model via FastAPI. Model artifacts under models/ are NOT
# baked into this image -- they're generated by `uv run python -m src.train`
# and mounted in at runtime (see README's "Docker" section), so the image
# doesn't need to be rebuilt every time the model is retrained.
FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir uv && \
    uv pip install --system --no-cache-dir -r requirements.txt

COPY src/ src/
COPY serve/ serve/

EXPOSE 8000

CMD ["uvicorn", "serve.main:app", "--host", "0.0.0.0", "--port", "8000"]
